package errors

import "errors"

/* Errors definition */
var (
	ErrDuplicatedUsername     = errors.New("duplicated username")
	ErrDuplicatedEmail        = errors.New("duplicated email")
	ErrDuplicatedAlias        = errors.New("duplicated alias")
	ErrDatabaseConnection     = errors.New("database connection error")
	ErrNotFound               = errors.New("entry not found")
	ErrUserNotFound           = errors.New("user not found")
	ErrWrongPassword          = errors.New("wrong password")
	ErrInvalidRequest         = errors.New("invalid request")
	ErrSessionExpired         = errors.New("the session is expired")
	ErrRedisConnection        = errors.New("redis connection error")
	ErrUnableToMarshal        = errors.New("unable to marshal the struct into JSON")
	ErrUnableToUnmarshal      = errors.New("unable to unmarshal the struct into JSON")
	ErrLoggedIn               = errors.New("the session has been logged with an account")
	ErrNotLoggedIn            = errors.New("the session hasn't been logged in yet")
	ErrPermissionDenied       = errors.New("permission denied")
	ErrCreateResourceFile     = errors.New("error occurs when create resource file")
	ErrWriteResourceFile      = errors.New("error occurs when write resource file")
	ErrInvalidFlagType        = errors.New("invalid flag type")
	ErrInvalidFlagSettings    = errors.New("invalid flag settings")
	ErrOutOfRange             = errors.New("parameter out of range")
	ErrPartlyFailed           = errors.New("procedure partly failed")
	ErrNotEnoughPoints        = errors.New("not enough points")
	ErrWriteConfigFile        = errors.New("fail to write config file")
	ErrNotMemberOfTeam        = errors.New("not a member of team")
	ErrNotAdminOfTeam         = errors.New("not team's admin")
	ErrMemberParticipated     = errors.New("some member has participated the specific contest")
	ErrTeamParticipated       = errors.New("your team has participated the contest")
	ErrDuplicatedName         = errors.New("duplicated name")
	ErrProcessed              = errors.New("the resource has been processed")
	ErrTimeout                = errors.New("the resource has expired")
	ErrAlreadyJoinedInTeam    = errors.New("the user has joined the team")
	ErrInvalidInvitationToken = errors.New("invalid invitation token")
	ErrNotInvited             = errors.New("the user has not been invited to this team")
	ErrAlreadyInvited         = errors.New("the user has been invited")
	ErrNoSuchApplication      = errors.New("no such application")
	ErrAlreadyApplied         = errors.New("the user has applied")
	ErrContestPending         = errors.New("the contest is pending")
	ErrContestStarted         = errors.New("the contest has started")
	ErrContestEnded           = errors.New("the contest has ended")
	ErrInvalidCaptchaFor      = errors.New("invalid captcha for")
	ErrCoolDown               = errors.New("cooling down")
	ErrInvalidCaptcha         = errors.New("invalid captcha")
	ErrNotInWhitelist         = errors.New("not in whitelist")
	ErrDangerousOperation     = errors.New("dangerous operation")
	ErrEmptyConfigKey         = errors.New("empty config key")
)
